# Generated by Django 5.0.6 on 2024-10-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('usuario', models.CharField(max_length=10, unique=True)),
                ('contrasena', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=40, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppUM.personal')),
                ('activo', models.BooleanField(default=True)),
            ],
            bases=('AppUM.personal',),
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppUM.personal')),
                ('jefe', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            bases=('AppUM.personal',),
        ),
    ]
