# Generated by Django 5.0.6 on 2024-10-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('motor', models.IntegerField()),
                ('estado', models.CharField(max_length=10)),
                ('kilometros', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=20)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('num_motor', models.CharField(max_length=20, unique=True)),
                ('num_chasis', models.CharField(max_length=20, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='motos/')),
                ('pertenece_tienda', models.BooleanField()),
                ('pertenece_taller', models.BooleanField()),
            ],
        ),
    ]
