# Generated by Django 5.0.6 on 2024-10-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0002_accesorio_moto'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='accesorios/'),
        ),
    ]
