# Generated by Django 5.0.6 on 2024-10-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0003_accesorio_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
