# Generated by Django 5.0.6 on 2024-10-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0006_moto_identificacion_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_UM', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_DM', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
