# Generated by Django 5.0.6 on 2024-10-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0007_logos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='num_chasis',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='num_motor',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
