# Generated by Django 5.0.6 on 2024-10-26 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0008_alter_moto_num_chasis_alter_moto_num_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
