# Generated by Django 5.0.6 on 2024-10-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0009_moto_fecha_ingreso_moto_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='motos/fotos/'),
        ),
    ]
