# Generated by Django 5.0.6 on 2024-11-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0011_accesorio_fecha_ingreso_accesorio_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=40)),
                ('calle', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('num_apartamento', models.IntegerField()),
            ],
        ),
    ]
