# Generated by Django 5.0.6 on 2024-11-01 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0012_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('principal', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='AppUM.cliente')),
            ],
        ),
    ]
