# Generated by Django 5.0.6 on 2024-11-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0013_clientecorreo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(unique=True)),
                ('principal', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_telefono', to='AppUM.cliente')),
            ],
        ),
    ]
