# Generated by Django 5.0.6 on 2024-11-01 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0014_clientetelefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecorreo',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_correo', to='AppUM.cliente'),
        ),
    ]
