# Generated by Django 5.0.6 on 2024-11-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0015_alter_clientecorreo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('padron', models.IntegerField(unique=True)),
                ('fotocopia_libreta', models.ImageField(blank=True, null=True, upload_to='documentacion/libretas/')),
                ('compra_venta', models.FileField(blank=True, null=True, upload_to='documentacion/compra_venta/')),
                ('certificado_venta', models.FileField(blank=True, null=True, upload_to='documentacion/certificado_venta/')),
                ('tipo', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_moto', to='AppUM.cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moto_cliente', to='AppUM.moto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clientemoto',
            constraint=models.UniqueConstraint(fields=('moto', 'cliente'), name='unique_moto_cliente'),
        ),
    ]
