# Generated by Django 5.0.6 on 2024-11-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0016_clientemoto_clientemoto_unique_moto_cliente'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientemoto',
            name='unique_moto_cliente',
        ),
        migrations.AlterUniqueTogether(
            name='clientemoto',
            unique_together={('moto', 'cliente')},
        ),
    ]
