# Generated by Django 5.0.6 on 2024-11-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0016_comprasventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientetelefono',
            name='telefono',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
