# Generated by Django 5.0.6 on 2024-11-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0017_remove_clientemoto_unique_moto_cliente_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClienteMoto',
            new_name='ComprasVentas',
        ),
    ]
