# Generated by Django 5.0.6 on 2024-11-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0018_remove_clientecorreo_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasventas',
            name='cantidad_cuotas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprasventas',
            name='cuotas_pagas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
