# Generated by Django 5.0.6 on 2024-11-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0019_comprasventas_cantidad_cuotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasventas',
            name='valor_cuota',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
