# Generated by Django 5.0.6 on 2024-11-12 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0020_comprasventas_valor_cuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('factura', models.IntegerField(null=True)),
                ('factura_rut', models.IntegerField(null=True)),
                ('factura_documento', models.FileField(blank=True, null=True, upload_to='documentacion/facturas_accesorios/')),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesorio_cliente', to='AppUM.accesorio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cliente', to='AppUM.cliente')),
            ],
        ),
    ]
