# Generated by Django 5.0.6 on 2024-11-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0021_clienteaccesorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
