# Generated by Django 5.0.6 on 2024-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0022_alter_personal_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='cantidad_pasajeros',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='moto',
            name='num_cilindros',
            field=models.IntegerField(default=1),
        ),
    ]
