# Generated by Django 5.0.6 on 2024-11-18 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0023_moto_cantidad_pasajeros_moto_num_cilindros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasventas',
            name='cantidad_cuotas',
        ),
        migrations.RemoveField(
            model_name='comprasventas',
            name='cuotas_pagas',
        ),
        migrations.RemoveField(
            model_name='comprasventas',
            name='valor_cuota',
        ),
        migrations.CreateModel(
            name='CuotasMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cuota', models.DateField()),
                ('fecha_prox_cuota', models.DateField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_cuotas', models.IntegerField()),
                ('cuotas_pagas', models.IntegerField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_venta', to='AppUM.comprasventas')),
            ],
        ),
    ]
