# Generated by Django 5.0.6 on 2024-11-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0025_comprasventas_forma_de_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasventas',
            name='padron',
        ),
    ]
