# Generated by Django 5.0.6 on 2024-11-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0026_remove_comprasventas_padron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculas',
            name='activo',
        ),
        migrations.AddField(
            model_name='matriculas',
            name='padron',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
