# Generated by Django 5.0.6 on 2024-11-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0027_remove_matriculas_activo_matriculas_padron'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuotasmoto',
            old_name='fecha_cuota',
            new_name='fecha_pago',
        ),
        migrations.RenameField(
            model_name='cuotasmoto',
            old_name='fecha_prox_cuota',
            new_name='fecha_prox_pago',
        ),
        migrations.RemoveField(
            model_name='cuotasmoto',
            name='cantidad_cuotas',
        ),
        migrations.RemoveField(
            model_name='cuotasmoto',
            name='cuotas_pagas',
        ),
        migrations.RemoveField(
            model_name='cuotasmoto',
            name='valor_cuota',
        ),
        migrations.AddField(
            model_name='cuotasmoto',
            name='cant_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuotasmoto',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
