# Generated by Django 5.0.6 on 2024-11-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0029_rename_cant_restante_cuotasmoto_cant_restante_dolares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotasmoto',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='documentacion/comprobantes/'),
        ),
    ]
