# Generated by Django 5.0.6 on 2024-11-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0030_cuotasmoto_comprobante_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='moneda_precio',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
    ]
