# Generated by Django 5.0.6 on 2024-11-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0031_moto_moneda_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_dolar_tienda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_dolar_taller', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
