# Generated by Django 5.0.6 on 2024-11-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0032_preciodolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='primera_sesion',
            field=models.BooleanField(default=False),
        ),
    ]
