# Generated by Django 5.0.6 on 2024-11-30 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0034_notificaciones_notificacionpersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apertura', models.DateTimeField()),
                ('cierre', models.DateTimeField(blank=True, null=True)),
                ('moneda', models.CharField(max_length=10)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depositos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('egresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_sistema', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_caja', to='AppUM.personal')),
            ],
        ),
    ]
