# Generated by Django 5.0.6 on 2024-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0036_movimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='tipo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
