# Generated by Django 5.0.6 on 2024-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0037_moto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotasmoto',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
