# Generated by Django 5.0.6 on 2024-12-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0038_cuotasmoto_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotasmoto',
            name='recargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
