# Generated by Django 5.0.6 on 2024-12-10 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0039_cuotasmoto_recargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotasAccesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('fecha_prox_pago', models.DateField()),
                ('moneda', models.CharField(default=True, max_length=10, null=True)),
                ('valor_pago_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pago_dolares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cant_restante_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cant_restante_dolares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_dolar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='documentacion/facturas_accesorios/')),
                ('metodo_pago', models.CharField(blank=True, max_length=20)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_accesorio', to='AppUM.clienteaccesorio')),
            ],
        ),
    ]
