# Generated by Django 5.0.6 on 2024-12-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0040_cuotasaccesorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='moneda_precio',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
    ]
