# Generated by Django 5.0.6 on 2024-12-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0041_accesorio_moneda_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('descripcion_ingreso', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20)),
                ('prioridad', models.CharField(blank=True, max_length=20)),
                ('fecha_estimada_cierre', models.DateField()),
                ('fecha_prox_servicio', models.DateField()),
                ('km_prox_servicio', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_servicio', to='AppUM.cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moto_servicio', to='AppUM.moto')),
            ],
        ),
        migrations.CreateModel(
            name='MecanicosServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecanicos_servicios', to='AppUM.mecanico')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_mecanicos', to='AppUM.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='TareasServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.TextField(blank=True, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_servicios', to='AppUM.servicios')),
            ],
        ),
    ]
