# Generated by Django 5.0.6 on 2024-12-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0043_servicios_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fecha_estimada_cierre',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_prox_servicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='km_prox_servicio',
            field=models.IntegerField(null=True),
        ),
    ]
