# Generated by Django 5.0.6 on 2024-12-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0044_alter_servicios_fecha_estimada_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
