# Generated by Django 5.0.6 on 2024-12-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0045_moto_precio_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_cuotas', models.IntegerField(default=1)),
                ('valor_cuota', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moneda_cuota', models.CharField(blank=True, max_length=20)),
                ('actual', models.BooleanField(default=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moto_financiamientos', to='AppUM.comprasventas')),
            ],
        ),
    ]
