# Generated by Django 5.0.6 on 2024-12-13 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0046_financiamientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotasmoto',
            name='recargo',
        ),
        migrations.RemoveField(
            model_name='financiamientos',
            name='venta',
        ),
        migrations.AddField(
            model_name='cuotasmoto',
            name='financiamiento',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, related_name='pago_financiamiento', to='AppUM.financiamientos'),
        ),
    ]
