# Generated by Django 5.0.6 on 2024-12-13 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0047_remove_cuotasmoto_recargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotasmoto',
            name='financiamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pago_financiamiento', to='AppUM.financiamientos'),
        ),
    ]
