# Generated by Django 5.0.6 on 2024-12-14 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0048_alter_cuotasmoto_financiamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotasmoto',
            name='financiamiento',
        ),
        migrations.AddField(
            model_name='financiamientos',
            name='venta',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, related_name='financiamientos_venta', to='AppUM.comprasventas'),
            preserve_default=False,
        ),
    ]
