# Generated by Django 5.0.6 on 2024-12-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0049_remove_cuotasmoto_financiamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotasFinanciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuota_financiamiento', to='AppUM.cuotasmoto')),
                ('financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financiamiento_cuota', to='AppUM.financiamientos')),
            ],
        ),
    ]
