# Generated by Django 5.0.6 on 2024-12-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0050_cuotasfinanciacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotasmoto',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
