# Generated by Django 5.0.6 on 2024-12-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0051_cuotasmoto_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamientos',
            name='inicial',
            field=models.BooleanField(default=False),
        ),
    ]
