# Generated by Django 5.0.6 on 2024-12-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0052_financiamientos_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamientos',
            name='precio_moto_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
