# Generated by Django 5.0.6 on 2024-12-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0053_financiamientos_precio_moto_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestosPiezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pieza', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
