# Generated by Django 5.0.6 on 2024-12-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0054_repuestospiezas'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestospiezas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
