# Generated by Django 5.0.6 on 2024-12-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0055_repuestospiezas_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
