# Generated by Django 5.0.6 on 2024-12-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0056_alter_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='num_apartamento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.AddField(
            model_name='cliente',
            name='domicilio',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
