# Generated by Django 5.0.6 on 2024-12-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0059_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='titulo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
