# Generated by Django 5.0.6 on 2024-12-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0060_servicios_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareasservicios',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
