# Generated by Django 5.0.6 on 2024-12-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0061_tareasservicios_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareasservicios',
            name='realizado',
            field=models.BooleanField(default=0),
        ),
    ]
