# Generated by Django 5.0.6 on 2024-12-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0062_tareasservicios_realizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanicosservicios',
            name='anotaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecanicosservicios',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
