# Generated by Django 5.0.6 on 2024-12-30 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0063_mecanicosservicios_anotaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecanicosservicios',
            name='anotaciones',
        ),
        migrations.RemoveField(
            model_name='mecanicosservicios',
            name='fecha',
        ),
        migrations.CreateModel(
            name='AnotacionesServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacion_mecanicos', to='AppUM.mecanico')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacion_servicio', to='AppUM.servicios')),
            ],
        ),
    ]
