# Generated by Django 5.0.6 on 2025-01-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0064_remove_mecanicosservicios_anotaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='contiene_num_chasis',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='moto',
            name='contiene_num_motor',
            field=models.BooleanField(default=1),
        ),
    ]
