# Generated by Django 5.0.6 on 2025-01-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0065_moto_contiene_num_chasis_moto_contiene_num_motor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareasservicios',
            name='precio',
        ),
        migrations.AddField(
            model_name='servicios',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
