# Generated by Django 5.0.6 on 2025-01-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0066_remove_tareasservicios_precio_servicios_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasventas',
            name='facturas',
            field=models.FileField(blank=True, null=True, upload_to='documentacion/facturas_motos/'),
        ),
    ]
