# Generated by Django 5.0.6 on 2025-01-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0067_comprasventas_facturas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotasmoto',
            name='fecha_prox_pago',
            field=models.DateField(null=True),
        ),
    ]
