# Generated by Django 5.0.6 on 2025-01-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0068_alter_cuotasmoto_fecha_prox_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fondo_dolares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fondo_pesos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
