# Generated by Django 5.0.6 on 2025-01-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0069_cliente_fondo_dolares_cliente_fondo_pesos'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='talle',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
