# Generated by Django 5.0.6 on 2025-01-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0070_accesorio_talle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotasaccesorios',
            name='fecha_prox_pago',
        ),
    ]
