# Generated by Django 5.0.6 on 2025-01-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0072_remove_repuestospiezas_tipo_pieza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestospiezas',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
