# Generated by Django 5.0.6 on 2025-01-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0073_repuestospiezas_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestospiezas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='repuestos_piezas/'),
        ),
    ]
