# Generated by Django 5.0.6 on 2025-01-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0074_repuestospiezas_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestosPiezasServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repuestopieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rp_servicios', to='AppUM.repuestospiezas')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_rp', to='AppUM.servicios')),
            ],
        ),
    ]
