# Generated by Django 5.0.6 on 2025-01-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0075_repuestospiezasservicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestospiezasservicios',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
