# Generated by Django 5.0.6 on 2025-01-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0076_repuestospiezasservicios_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecorreo',
            name='correo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientetelefono',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
