# Generated by Django 5.0.6 on 2025-01-13 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0077_alter_clientecorreo_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFondos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(default=True, max_length=10, null=True)),
                ('ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_fondos', to='AppUM.cliente')),
            ],
        ),
    ]
