# Generated by Django 5.0.6 on 2025-01-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0078_clientefondos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientefondos',
            old_name='ingreso',
            new_name='ingreso_dolares',
        ),
        migrations.RenameField(
            model_name='clientefondos',
            old_name='total',
            new_name='ingreso_pesos',
        ),
        migrations.AddField(
            model_name='clientefondos',
            name='total_dolares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clientefondos',
            name='total_pesos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
