# Generated by Django 5.0.6 on 2025-01-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0080_clientefondos_comprobante_clientefondos_metodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fondo_dolares',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fondo_pesos',
        ),
    ]
