# Generated by Django 5.0.6 on 2025-01-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0081_remove_cliente_fondo_dolares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionpersonal',
            name='leido',
            field=models.BooleanField(default=0),
        ),
    ]
