# Generated by Django 5.0.6 on 2025-01-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0083_auto_20250115_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestospiezas',
            name='stock_critico',
            field=models.IntegerField(null=True),
        ),
    ]
