# Generated by Django 5.0.6 on 2025-01-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0084_repuestospiezas_stock_critico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteRepuestosPiezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_rp', to='AppUM.cliente')),
                ('repuestospiezas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_cliente', to='AppUM.repuestospiezas')),
            ],
        ),
    ]
