# Generated by Django 5.0.6 on 2025-02-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0086_clienterepuestospiezas_fecha_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='padron',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
