# Generated by Django 5.0.6 on 2025-02-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0087_alter_matriculas_padron'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteaccesorio',
            name='codigo_compra',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
