# Generated by Django 5.0.6 on 2025-02-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0088_clienteaccesorio_codigo_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.TextField(blank=True, null=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='movimientos',
            name='metodo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='moneda',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='rubro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
