# Generated by Django 5.0.6 on 2025-02-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0089_rubros_movimientos_metodo_movimientos_moneda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='es_accesorio',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='es_moto',
            field=models.BooleanField(default=0),
        ),
    ]
