# Generated by Django 5.0.6 on 2025-02-28 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0090_movimientos_es_accesorio_movimientos_es_moto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoPagoMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_pago_accesorio', to='AppUM.movimientos')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_accesorio_movimiento', to='AppUM.cuotasaccesorios')),
            ],
        ),
    ]
