# Generated by Django 5.0.6 on 2025-02-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0091_movimientopagomoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientopagomoto',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_pago_moto', to='AppUM.movimientos'),
        ),
        migrations.AlterField(
            model_name='movimientopagomoto',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_moto_movimiento', to='AppUM.cuotasmoto'),
        ),
        migrations.CreateModel(
            name='MovimientoPagoAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_pago_accesorio', to='AppUM.movimientos')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_accesorio_movimiento', to='AppUM.cuotasaccesorios')),
            ],
        ),
    ]
