# Generated by Django 5.0.6 on 2025-03-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0092_alter_movimientopagomoto_movimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubros',
            name='cantidad_usos',
            field=models.IntegerField(default=0),
        ),
    ]
