# Generated by Django 5.0.6 on 2025-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0093_rubros_cantidad_usos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotasmoto',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
