# Generated by Django 5.0.6 on 2025-03-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0094_alter_cuotasmoto_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='seleccionado',
            field=models.BooleanField(default=0),
        ),
    ]
