# Generated by Django 5.0.6 on 2025-03-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0095_accesorio_seleccionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteaccesorio',
            name='forma_de_pago',
            field=models.TextField(blank=True, null=True),
        ),
    ]
