# Generated by Django 5.0.6 on 2025-03-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0096_clienteaccesorio_forma_de_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotasaccesorios',
            name='mostrar_reporte',
            field=models.BooleanField(default=1),
        ),
    ]
