# Generated by Django 5.0.6 on 2025-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0097_cuotasaccesorios_mostrar_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='cantidad_pasajeros',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='kilometros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
