# Generated by Django 5.0.6 on 2025-04-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0098_alter_moto_anio_alter_moto_cantidad_pasajeros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamientos',
            name='quincena',
            field=models.BooleanField(default=False),
        ),
    ]
