# Generated by Django 5.0.6 on 2025-04-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0099_financiamientos_quincena'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotasaccesorios',
            name='fecha_prox_pago',
            field=models.DateField(null=True),
        ),
    ]
