# Generated by Django 5.0.6 on 2025-05-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0100_cuotasaccesorios_fecha_prox_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
