# Generated by Django 5.0.6 on 2025-05-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0101_notificaciones_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(default='Cliente', max_length=500),
        ),
    ]
