# Generated by Django 5.0.6 on 2025-05-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0102_cliente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamientos',
            name='semanal',
            field=models.BooleanField(default=False),
        ),
    ]
