# Generated by Django 5.0.6 on 2025-05-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0103_financiamientos_semanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
