# Generated by Django 5.0.6 on 2025-05-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0105_presupuestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='presupuestos/'),
        ),
    ]
