# Generated by Django 5.0.6 on 2025-06-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0106_alter_presupuestos_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='padron',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
