# Generated by Django 5.0.6 on 2025-06-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0107_alter_matriculas_padron'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='anio',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='apellido',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='documento',
            field=models.CharField(default=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='fuente_precios',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='mano_de_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='marca',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='matricula',
            field=models.CharField(default=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='modelo',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='moneda',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='nombre',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='num_chasis',
            field=models.CharField(default=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='num_motor',
            field=models.CharField(default=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='padron',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='precio_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='texto',
            field=models.TextField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='NotasPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.CharField(max_length=200)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_presupuesto', to='AppUM.presupuestos')),
            ],
        ),
        migrations.CreateModel(
            name='PiezasPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piezas', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('moneda', models.CharField(default=True, max_length=10, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas_presupuesto', to='AppUM.presupuestos')),
            ],
        ),
    ]
