# Generated by Django 5.0.6 on 2025-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0108_presupuestos_anio_presupuestos_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='tipo_doc',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
    ]
