# Generated by Django 5.0.6 on 2025-06-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0109_presupuestos_tipo_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestos',
            name='documento',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='matricula',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='num_chasis',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='num_motor',
            field=models.CharField(default=True, max_length=40),
        ),
    ]
