# Generated by Django 5.0.6 on 2025-06-21 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0110_alter_presupuestos_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojasMembretadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('texto', models.TextField(blank=True, default=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='hojas_membretadas/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_hoja_membretada', to='AppUM.personal')),
            ],
        ),
    ]
