# Generated by Django 5.0.6 on 2025-06-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUM', '0111_hojasmembretadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojasmembretadas',
            name='fecha',
            field=models.DateField(default='2025-06-21'),
            preserve_default=False,
        ),
    ]
